language: php

php:
  - 7.0

services:
  - mysql
  - redis

addons:
  code_climate:
    repo_token: ed66781603cdad4678f641626c7bc1dda3f42e39e460f9606f0d3e0f442cc658

before_install:
  - mysql -e "create database IF NOT EXISTS swapp;" -uroot

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

notifications:
  on_success: never
  on_failure: always
